kind: Deployment
metadata:
  name: my-ak-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: angular-app
  template:
    metadata:
      labels:
        app: angular-app
    spec:
      containers:
      - name: my-angular-app
        image: 519852036875.dkr.ecr.us-east-1.amazonaws.com/my-first-ecr:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 8085
# service type loadbalancer
---
apiVersion: v1
kind: Service
metadata:
  name: angular-app-svc
spec:
  selector:
    app: angular-app
  ports:
    - protocol: TCP
      port: 8085
      targetPort: 8085
  type: ClusterIP
---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  annotations:
    kubernetes.io/ingress.class:  "public"
  name: angular-app
  namespace: default
spec:
  rules:
    - host: www.pasivadipranam.tk
      http:
        paths:
          - backend:
              serviceName: angular-app-svc
              servicePort: 8085
            path: /

