# sample ci for springboot application
name: Java CI with Maven

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  pull_request_review:
    types: [submitted]

jobs:
  build:

    if: github.event.review.state == 'approved'
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Set up JDK 11
      uses: actions/setup-java@v3
      with:
        java-version: '11'
        distribution: 'temurin'
        cache: maven
    - name: Build with Maven
      run: |
       mvn -Bpackage --file pom.xml
       mkdir artifacts && cp target/*.jar artifacts
       cd artifacts && ls
    - name: Build and Push Docker image
      if: "contains(github.event.head_commit.message, 'BUILD_CONTAINER_IMAGE')"
      uses: mr-smithers-excellent/docker-build-push@v4
      with:
        image: nayab786/github-actions
        registry: docker.io
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
